# Generated by Django 5.1.6 on 2025-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeetCodeUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("total_solved", models.IntegerField(default=0)),
                ("easy_solved", models.IntegerField(default=0)),
                ("medium_solved", models.IntegerField(default=0)),
                ("hard_solved", models.IntegerField(default=0)),
                ("topics", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
