# Generated by Django 5.1.6 on 2025-03-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="urls",
            new_name="Question_Link",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="solution_url",
            new_name="solution",
        ),
        migrations.AlterField(
            model_name="question",
            name="acceptance_rate",
            field=models.FloatField(default=0),
        ),
    ]
